### ISSUE TITLE
您好，请问能否提供无线网卡的具体型号或者淘宝链接

### ISSUE THREAD

**Issue by wintopzuo** [masonsxu/Hackintosh-Lenovo-Chao5000#2]
我看到淘宝上按您提供的型号，有很多的不同的无线网卡，能否提供下具体的淘宝地址？

**Comment by masonsxu** [comment]
我和同学换的😬，没有走淘宝买，你可以查一下那些网卡免驱或者有相关驱动的，买一个相应型号的就行，价格可能不一样。这个看自己了。

**Comment by lijian-github** [comment]
原机网卡可以直接用
