### ISSUE TITLE
请问小新潮5000是否需要刷bios 白名单才能使用ntel@ac3168无线网卡？

### ISSUE THREAD

**Issue by wintopzuo** [masonsxu/Hackintosh-Lenovo-Chao5000#3]
RT。
后天到货，请教下

**Comment by masonsxu** [comment]
不需要刷bios，直接换就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [masonsxu/Hackintosh-Lenovo-Chao5000] 请问小新潮5000是否需要刷bios ***@***.***无线网卡？ (#3)




 
RT。
 后天到货，请教下

**Comment by wintopzuo** [comment]
感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年3月16日 22:57
收件人: ***@***.***>
抄送: wintopzuo<mailto:******@Live.com>; ***@***.***>
主题: Re: [masonsxu/Hackintosh-Lenovo-Chao5000] 请问小新潮5000是否需要刷bios ***@***.***无线网卡？ (#3)

不需要刷bios，直接换就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [masonsxu/Hackintosh-Lenovo-Chao5000] 请问小新潮5000是否需要刷bios ***@***.***无线网卡？ (#3)





RT。
后天到货，请教下

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
