### ISSUE TITLE
请问用U盘引导OC启动后，卡在白苹果logo的界面不动，如何处理？

### ISSUE THREAD

**Issue by wintopzuo** [masonsxu/Hackintosh-Lenovo-Chao5000#4]
rt.

**Comment by masonsxu** [comment]
1、使用OC引导文件的编辑工具，打开 -v，查看卡在哪个位置，查询解决办法进行解决；
2、如果没有办法修改OC引导的配置文件，找一个你可以进入系统的EFI引导文件进入系统，然后进行修改。（首先保证可以进入系统，后续再慢慢完善。）

**Comment by wintopzuo** [comment]
`			<dict>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args -v</key>
				<string>igfxrpsc=1 igfxonln=1</string>
				<key>csr-active-config</key>
				<data>5wMAAA==</data>
				<key>prev-lang:kbd</key>
				<data>emgtSGFuczoyNTI=</data>
				<key>run-efi-updater</key>
				<string>No</string>
			</dict>`
已经打开了 -v，选择uefi启动后，显示白苹果logo 就不动了 ，没任何位置提示。

**Comment by masonsxu** [comment]
> `<dict> <key>SystemAudioVolume</key> <data>Rg==</data> <key>boot-args -v</key> <string>igfxrpsc=1 igfxonln=1</string> <key>csr-active-config</key> <data>5wMAAA==</data> <key>prev-lang:kbd</key> <data>emgtSGFuczoyNTI=</data> <key>run-efi-updater</key> <string>No</string> </dict>`
> 已经打开了 -v，选择uefi启动后，显示白苹果logo 就不动了 ，没任何位置提示。

请参考：#5
