### ISSUE TITLE
打开-V，错误如下，请支招下。

### ISSUE THREAD

**Issue by wintopzuo** [masonsxu/Hackintosh-Lenovo-Chao5000#5]
![微信图片_20210320140117](https://user-images.githubusercontent.com/42713901/111860793-f429ca80-8984-11eb-98ca-69b99c65907a.jpg)

error:OS.dmg.root_hash

**Comment by masonsxu** [comment]
bios设置了吗？没有的话设置一下。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月20日 14:06:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [masonsxu/Hackintosh-Lenovo-Chao5000] 打开-V，错误如下，请支招下。 (#5)




 

 
error:OS.dmg.root_hash

**Comment by wintopzuo** [comment]
你好，已经做了相关设置，禁用虚拟，关闭安全启动等。是不是bios 有个什么锁，需要用第三方工具解开呢？

**Comment by masonsxu** [comment]
CFg锁尽量改一下，能用CPU睿频和原生电源管理。我有写教程
，可以去看一下。
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月20日 18:05:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [masonsxu/Hackintosh-Lenovo-Chao5000] 打开-V，错误如下，请支招下。 (#5)




 
你好，已经做了相关设置，禁用虚拟，关闭安全启动等。是不是bios 有个什么锁，需要用第三方工具解开呢？

**Comment by wintopzuo** [comment]
已经解决，装完了。修改 config 把 带 cfg 的都关闭了，就正常了。感谢

**Comment by masonsxu** [comment]
嗯嗯，不过睿频也不难，你以后有时间了可以试一下。README里面大部分的配置我都留有教程链接。
