### ISSUE TITLE
请教这个uefi 支持双显卡吗？

### ISSUE THREAD

**Issue by wintopzuo** [masonsxu/Hackintosh-Lenovo-Chao5000#6]
现在用的核显，可以正常操作使用。
开启独立显卡会无限重启，不知道支持不支持。

**Comment by masonsxu** [comment]
这个需要看显卡有没有支持的驱动，我的不被支持，所以只能核显。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月21日 02:16:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [masonsxu/Hackintosh-Lenovo-Chao5000] 请教这个uefi 支持双显卡吗？ (#6)




 
现在用的核显，可以正常操作使用。
 开启独立显卡会无限重启，不知道支持不支持。
