### ISSUE TITLE
请问这个支持i5-7200U的chao 5000吗

### ISSUE THREAD

**Issue by 15909692936** [masonsxu/Hackintosh-Lenovo-Chao5000#7]

**Comment by masonsxu** [comment]
可以尝试，先把bios设置好。然后看触摸板ID和其他配置是否和我的一样。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月31日(周三) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [masonsxu/Hackintosh-Lenovo-Chao5000] 请问这个支持i5-7200U的chao 5000吗 (#7)
