### ISSUE TITLE
HDMI外接显示器不显示。

### ISSUE THREAD

**Issue by lijian-github** [masonsxu/Hackintosh-Lenovo-Chao5000#8]
HDMI外接显示器不显示。

**Comment by lky182** [comment]
请问解决了吗，我也是同样问题。

**Comment by lky182** [comment]
> HDMI外接显示器不显示。

请问解决了吗 我也是一样的问题

**Comment by masonsxu** [comment]
手头没有外屏供我做测试，所以没有做这方面的适配，如果你解决了这个问题，还请给我说一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 凌晨1:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [masonsxu/Hackintosh-Lenovo-Chao5000] HDMI外接显示器不显示。 (#8)




  
HDMI外接显示器不显示。
  
请问解决了吗 我也是一样的问题

**Comment by 52Hz-Kun** [comment]
我这HDMI也不显示，您能提供下思路该怎么改吗，我刚玩还不太会搞，还有触摸屏不管用是要替换哪个驱动呢？谢谢~

**Comment by masonsxu** [comment]
> HDMI外接显示器不显示。



> > HDMI外接显示器不显示。
> 
> 请问解决了吗 我也是一样的问题

听取群里好友的解决方式，将电脑机型修改为14,1以后可能可以解决HDMI的问题，最新版本的EFI引导我已经发布了，大家可以试一下。

**Comment by lijian-github** [comment]
> > HDMI外接显示器不显示。
> 
> > > HDMI外接显示器不显示。
> > 
> > 
> > 请问解决了吗 我也是一样的问题
> 
> 听取群里好友的解决方式，将电脑机型修改为14,1以后可能可以解决HDMI的问题，最新版本的EFI引导我已经发布了，大家可以试一下。

最新版本的EFI引导解决了这个问题了。。。
